In [14]:
import pandas as pd
import zstandard as zstd

file_path = "/data/market_data/binance/future/XRPUSDT/book_ticker/binance-futures_book_ticker_2026-03-31_XRPUSDT.csv.zst"

with open(file_path, 'rb') as f:
    dctx = zstd.ZstdDecompressor()
    stream_reader = dctx.stream_reader(f)
    df = pd.read_csv(stream_reader)
    stream_reader.close()

df

,exchange,symbol,timestamp,local_timestamp,ask_amount,ask_price,bid_price,bid_amount
0,binance-futures,XRPUSDT,1774915200034000,1774915200037764,8623.6,1.3235,1.3234,47333.7
1,binance-futures,XRPUSDT,1774915200037000,1774915200039805,8615.9,1.3235,1.3234,47333.7
2,binance-futures,XRPUSDT,1774915200045000,1774915200048098,8615.9,1.3235,1.3234,47338.3
3,binance-futures,XRPUSDT,1774915200061000,1774915200064224,8615.9,1.3235,1.3234,47330.8
4,binance-futures,XRPUSDT,1774915200067000,1774915200069822,8615.9,1.3235,1.3234,43038.8
...,...,...,...,...,...,...,...,...
6208359,binance-futures,XRPUSDT,1775001599888000,1775001599891442,6803.4,1.3404,1.3403,42031.9
6208360,binance-futures,XRPUSDT,1775001599890000,1775001599892523,6791.0,1.3404,1.3403,42031.9
6208361,binance-futures,XRPUSDT,1775001599891000,1775001599893967,6803.4,1.3404,1.3403,42031.9
6208362,binance-futures,XRPUSDT,1775001599893000,1775001599895995,10254.0,1.3404,1.3403,42031.9
6208363,binance-futures,XRPUSDT,1775001599993000,1775001599995983,10254.0,1.3404,1.3403,40831.9

In [3]:
import pandas as pd
df2 = pd.read_csv("/data/market_data/binance/future/XRPUSDT/book_ticker/binance-futures_book_ticker_2026-01-01_XRPUSDT.csv.gz")
df2

,exchange,symbol,timestamp,local_timestamp,ask_amount,ask_price,bid_price,bid_amount
0,binance-futures,XRPUSDT,1767225600068000,1767225600072357,5683.5,1.8411,1.8410,64526.2
1,binance-futures,XRPUSDT,1767225601573000,1767225601576000,5683.5,1.8411,1.8410,64615.6
2,binance-futures,XRPUSDT,1767225601580000,1767225601583293,5817.1,1.8411,1.8410,64615.6
3,binance-futures,XRPUSDT,1767225601589000,1767225601593218,5815.2,1.8411,1.8410,64615.6
4,binance-futures,XRPUSDT,1767225601684000,1767225601686784,5681.6,1.8411,1.8410,64615.6
...,...,...,...,...,...,...,...,...
4372165,binance-futures,XRPUSDT,1767311999975000,1767311999978843,65057.7,1.8792,1.8791,12515.5
4372166,binance-futures,XRPUSDT,1767311999977000,1767311999981160,65030.7,1.8792,1.8791,12515.5
4372167,binance-futures,XRPUSDT,1767311999980000,1767311999983245,65057.7,1.8792,1.8791,12515.5
4372168,binance-futures,XRPUSDT,1767311999981000,1767311999984108,65057.7,1.8792,1.8791,12492.9
4372169,binance-futures,XRPUSDT,1767311999982000,1767311999985239,65030.7,1.8792,1.8791,12492.9

In [8]:
df2.dtypes

exchange            object
symbol              object
timestamp            int64
local_timestamp      int64
ask_amount         float64
ask_price          float64
bid_price          float64
bid_amount         float64
dtype: object

In [4]:
# 检查是否有重复值
has_duplicates = df2["timestamp"].duplicated().any()
print("是否有重复值:", has_duplicates)

# 检查是否递增
is_monotonic = df2["timestamp"].is_monotonic_increasing
print("是否递增:", is_monotonic)

是否有重复值: True
是否递增: True

In [6]:
import pandas as pd
df2 = pd.read_csv("/data/market_data/binance/future/XRPUSDT/book_snapshot_25/binance-futures_book_snapshot_25_2026-03-19_XRPUSDT.csv.gz")
df2

,exchange,symbol,timestamp,local_timestamp,asks[0].price,asks[0].amount,bids[0].price,bids[0].amount,asks[1].price,asks[1].amount,...,bids[22].price,bids[22].amount,asks[23].price,asks[23].amount,bids[23].price,bids[23].amount,asks[24].price,asks[24].amount,bids[24].price,bids[24].amount
0,binance-futures,XRPUSDT,1773878402332000,1773878403475208,1.4642,13888.1,1.4641,11576.9,1.4643,25360.6,...,1.4619,34460.5,1.4665,101193.6,1.4618,76846.5,1.4666,38409.7,1.4617,100007.2
1,binance-futures,XRPUSDT,1773878403490000,1773878403491955,1.4640,19640.1,1.4639,7846.7,1.4641,38197.2,...,1.4617,100007.2,1.4663,26484.1,1.4616,147844.0,1.4664,46642.2,1.4615,51164.7
2,binance-futures,XRPUSDT,1773878403542000,1773878403545228,1.4640,11304.2,1.4639,11738.8,1.4641,24960.3,...,1.4617,100007.2,1.4663,26484.1,1.4616,147844.0,1.4664,46642.2,1.4615,51164.7
3,binance-futures,XRPUSDT,1773878403596000,1773878403598928,1.4640,13962.0,1.4639,11723.9,1.4641,25870.5,...,1.4617,100007.2,1.4663,26484.1,1.4616,147844.0,1.4664,46642.2,1.4615,51164.7
4,binance-futures,XRPUSDT,1773878403650000,1773878403653354,1.4640,13962.0,1.4639,11723.9,1.4641,25870.5,...,1.4617,100007.2,1.4663,26484.1,1.4616,147844.0,1.4664,46642.2,1.4615,51164.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1420788,binance-futures,XRPUSDT,1773964799536000,1773964799538023,1.4469,58628.2,1.4468,12433.1,1.4470,27302.1,...,1.4446,41397.0,1.4492,53738.6,1.4445,67205.3,1.4493,167787.0,1.4444,35557.1
1420789,binance-futures,XRPUSDT,1773964799588000,1773964799589649,1.4469,58628.2,1.4468,12433.1,1.4470,27302.1,...,1.4446,41397.0,1.4492,53738.6,1.4445,67205.3,1.4493,167787.0,1.4444,35557.1
1420790,binance-futures,XRPUSDT,1773964799640000,1773964799641666,1.4469,58628.2,1.4468,12433.1,1.4470,27302.1,...,1.4446,41397.0,1.4492,53738.6,1.4445,67205.3,1.4493,167787.0,1.4444,35557.1
1420791,binance-futures,XRPUSDT,1773964799744000,1773964799745736,1.4469,58628.2,1.4468,12433.1,1.4470,27302.1,...,1.4446,41397.0,1.4492,53738.6,1.4445,67205.3,1.4493,167787.0,1.4444,35557.1
1420792,binance-futures,XRPUSDT,1773964799968000,1773964799969623,1.4469,58628.2,1.4468,12433.1,1.4470,27302.1,...,1.4446,41397.0,1.4492,53738.6,1.4445,67205.3,1.4493,167787.0,1.4444,35557.1

In [7]:
import json

with open("/data/sigma/sigma/basic/binance_assets.json", "r") as f:
    assets = json.load(f)
assets

{'spot': {'ETHBTC': {'tick_size': 1e-05, 'lot_size': 0.0001},
  'LTCBTC': {'tick_size': 1e-06, 'lot_size': 0.001},
  'BNBBTC': {'tick_size': 1e-06, 'lot_size': 0.001},
  'NEOBTC': {'tick_size': 1e-08, 'lot_size': 0.01},
  'QTUMETH': {'tick_size': 1e-07, 'lot_size': 0.1},
  'EOSETH': {'tick_size': 1e-07, 'lot_size': 0.1},
  'SNTETH': {'tick_size': 1e-08, 'lot_size': 1.0},
  'BNTETH': {'tick_size': 1e-07, 'lot_size': 0.1},
  'BCCBTC': {'tick_size': 1e-06, 'lot_size': 0.001},
  'GASBTC': {'tick_size': 1e-07, 'lot_size': 0.1},
  'BNBETH': {'tick_size': 0.0001, 'lot_size': 0.001},
  'BTCUSDT': {'tick_size': 0.01, 'lot_size': 1e-05},
  'ETHUSDT': {'tick_size': 0.01, 'lot_size': 0.0001},
  'HSRBTC': {'tick_size': 1e-06, 'lot_size': 0.01},
  'OAXETH': {'tick_size': 1e-07, 'lot_size': 1.0},
  'DNTETH': {'tick_size': 1e-08, 'lot_size': 1.0},
  'MCOETH': {'tick_size': 1e-06, 'lot_size': 0.01},
  'ICNETH': {'tick_size': 1e-07, 'lot_size': 1.0},
  'MCOBTC': {'tick_size': 1e-07, 'lot_size': 0.01},
  'WTCBTC': {'tick_size': 1e-08, 'lot_size': 1.0},
  'WTCETH': {'tick_size': 1e-06, 'lot_size': 0.01},
  'LRCBTC': {'tick_size': 1e-08, 'lot_size': 1.0},
  'LRCETH': {'tick_size': 1e-08, 'lot_size': 1.0},
  'QTUMBTC': {'tick_size': 1e-08, 'lot_size': 0.1},
  'YOYOBTC': {'tick_size': 1e-08, 'lot_size': 1.0},
  'OMGBTC': {'tick_size': 1e-07, 'lot_size': 0.1},
  'OMGETH': {'tick_size': 1e-06, 'lot_size': 0.1},
  'ZRXBTC': {'tick_size': 1e-08, 'lot_size': 1.0},
  'ZRXETH': {'tick_size': 1e-07, 'lot_size': 1.0},
  'STRATBTC': {'tick_size': 1e-08, 'lot_size': 1.0},
  'STRATETH': {'tick_size': 1e-06, 'lot_size': 0.01},
  'SNGLSBTC': {'tick_size': 1e-08, 'lot_size': 1.0},
  'SNGLSETH': {'tick_size': 1e-08, 'lot_size': 1.0},
  'BQXBTC': {'tick_size': 1e-08, 'lot_size': 1.0},
  'BQXETH': {'tick_size': 10.0, 'lot_size': 10.0},
  'KNCBTC': {'tick_size': 1e-08, 'lot_size': 0.1},
  'KNCETH': {'tick_size': 1e-07, 'lot_size': 0.1},
  'FUNBTC': {'tick_size': 1e-08, 'lot_size': 1.0},
  'FUNETH': {'tick_size': 1e-08, 'lot_size': 1.0},
  'SNMBTC': {'tick_size': 1e-08, 'lot_size': 1.0},
  'SNMETH': {'tick_size': 1e-08, 'lot_size': 1.0},
  'NEOETH': {'tick_size': 1e-06, 'lot_size': 0.01},
  'IOTABTC': {'tick_size': 1e-08, 'lot_size': 1.0},
  'IOTAETH': {'tick_size': 1e-08, 'lot_size': 1.0},
  'LINKBTC': {'tick_size': 1e-07, 'lot_size': 0.01},
  'LINKETH': {'tick_size': 1e-06, 'lot_size': 0.01},
  'XVGBTC': {'tick_size': 1e-08, 'lot_size': 1.0},
  'XVGETH': {'tick_size': 1e-08, 'lot_size': 1.0},
  'SALTBTC': {'tick_size': 1e-07, 'lot_size': 0.01},
  'SALTETH': {'tick_size': 1e-06, 'lot_size': 0.01},
  'MDABTC': {'tick_size': 1e-08, 'lot_size': 1.0},
  'MDAETH': {'tick_size': 1e-07, 'lot_size': 1.0},
  'MTLBTC': {'tick_size': 1e-08, 'lot_size': 0.1},
  'MTLETH': {'tick_size': 1e-07, 'lot_size': 0.1},
  'SUBBTC': {'tick_size': 1e-08, 'lot_size': 1.0},
  'SUBETH': {'tick_size': 1e-08, 'lot_size': 1.0},
  'EOSBTC': {'tick_size': 1e-08, 'lot_size': 0.1},
  'SNTBTC': {'tick_size': 1e-08, 'lot_size': 1.0},
  'ETCETH': {'tick_size': 1e-05, 'lot_size': 0.01},
  'ETCBTC': {'tick_size': 1e-07, 'lot_size': 0.01},
  'MTHBTC': {'tick_size': 1e-08, 'lot_size': 1.0},
  'MTHETH': {'tick_size': 1e-08, 'lot_size': 1.0},
  'ENGBTC': {'tick_size': 1e-08, 'lot_size': 1.0},
  'ENGETH': {'tick_size': 1e-07, 'lot_size': 1.0},
  'DNTBTC': {'tick_size': 1e-08, 'lot_size': 1.0},
  'ZECBTC': {'tick_size': 1e-07, 'lot_size': 0.001},
  'ZECETH': {'tick_size': 1e-05, 'lot_size': 0.001},
  'BNTBTC': {'tick_size': 1e-08, 'lot_size': 0.1},
  'ASTBTC': {'tick_size': 1e-08, 'lot_size': 1.0},
  'ASTETH': {'tick_size': 1e-07, 'lot_size': 1.0},
  'DASHBTC': {'tick_size': 1e-07, 'lot_size': 0.001},
  'DASHETH': {'tick_size': 1e-05, 'lot_size': 0.001},
  'OAXBTC': {'tick_size': 1e-08, 'lot_size': 1.0},
  'ICNBTC': {'tick_size': 1e-08, 'lot_size': 1.0},
  'BTGBTC': {'tick_size': 1e-06, 'lot_size': 0.01},
  'BTGETH': {'tick_size': 1e-06, 'lot_size': 0.01},
  'EVXBTC': {'tick_size': 1e-08, 'lot_size': 1.0},
  'EVXETH': {'tick_size': 1e-07, 'lot_size': 1.0},
  'REQBTC': {'tick_size': 1e-08, 'lot_size': 1.0},
  'REQETH': {'tick_size': 1e-08, 'lot_size': 1.0},
  'VIBBTC': {'tick_size': 1e-08, 'lot_size': 1.0},
  'VIBETH': {'tick_size': 1e-08, 'lot_size': 1.0},
  'HSRETH': {'tick_size': 1e-06, 'lot_size': 0.01},
  'TRXBTC': {'tick_size': 1e-08, 'lot_size': 1.0},
  'TRXETH': {'tick_size': 1e-08, 'lot_size': 1.0},
  'POWRBTC': {'tick_size': 1e-08, 'lot_size': 1.0},
  'POWRETH': {'tick_size': 1e-07, 'lot_size': 1.0},
  'ARKBTC': {'tick_size': 1e-08, 'lot_size': 0.1},
  'ARKETH': {'tick_size': 1e-06, 'lot_size': 0.01},
  'YOYOETH': {'tick_size': 1e-08, 'lot_size': 1.0},
  'XRPBTC': {'tick_size': 1e-08, 'lot_size': 0.1},
  'XRPETH': {'tick_size': 1e-07, 'lot_size': 0.1},
  'MODBTC': {'tick_size': 1e-07, 'lot_size': 0.01},
  'MODETH': {'tick_size': 1e-06, 'lot_size': 0.01},
  'ENJBTC': {'tick_size': 1e-08, 'lot_size': 0.1},
  'ENJETH': {'tick_size': 1e-08, 'lot_size': 0.1},
  'STORJBTC': {'tick_size': 1e-08, 'lot_size': 1.0},
  'STORJETH': {'tick_size': 1e-07, 'lot_size': 1.0},
  'BNBUSDT': {'tick_size': 0.01, 'lot_size': 0.001},
  'VENBNB': {'tick_size': 0.0001, 'lot_size': 0.01},
  'YOYOBNB': {'tick_size': 1e-06, 'lot_size': 1.0},
  'POWRBNB': {'tick_size': 1e-06, 'lot_size': 1.0},
  'VENBTC': {'tick_size': 1e-08, 'lot_size': 1.0},
  'VENETH': {'tick_size': 1e-08, 'lot_size': 1.0},
  'KMDBTC': {'tick_size': 1e-08, 'lot_size': 1.0},
  'KMDETH': {'tick_size': 1e-07, 'lot_size': 1.0},
  'NULSBNB': {'tick_size': 1e-05, 'lot_size': 0.1},
  'RCNBTC': {'tick_size': 1e-08, 'lot_size': 1.0},
  'RCNETH': {'tick_size': 1e-08, 'lot_size': 1.0},
  'RCNBNB': {'tick_size': 1e-06, 'lot_size': 1.0},
  'NULSBTC': {'tick_size': 1e-08, 'lot_size': 1.0},
  'NULSETH': {'tick_size': 1e-08, 'lot_size': 1.0},
  'RDNBTC': {'tick_size': 1e-08, 'lot_size': 1.0},
  'RDNETH': {'tick_size': 1e-07, 'lot_size': 1.0},
  'RDNBNB': {'tick_size': 1e-05, 'lot_size': 0.1},
  'XMRBTC': {'tick_size': 1e-06, 'lot_size': 0.001},
  'XMRETH': {'tick_size': 1e-05, 'lot_size': 0.001},
  'DLTBNB': {'tick_size': 1e-06, 'lot_size': 1.0},
  'WTCBNB': {'tick_size': 1e-06, 'lot_size': 0.1},
  'DLTBTC': {'tick_size': 1e-08, 'lot_size': 1.0},
  'DLTETH': {'tick_size': 1e-08, 'lot_size': 1.0},
  'AMBBTC': {'tick_size': 1e-08, 'lot_size': 1.0},
  'AMBETH': {'tick_size': 1e-08, 'lot_size': 1.0},
  'AMBBNB': {'tick_size': 1e-06, 'lot_size': 1.0},
  'BCCETH': {'tick_size': 1e-05, 'lot_size': 0.001},
  'BCCUSDT': {'tick_size': 0.01, 'lot_size': 1e-05},
  'BCCBNB': {'tick_size': 0.01, 'lot_size': 1e-05},
  'BATBTC': {'tick_size': 1e-08, 'lot_size': 1.0},
  'BATETH': {'tick_size': 1e-07, 'lot_size': 1.0},
  'BATBNB': {'tick_size': 1e-06, 'lot_size': 1.0},
  'BCPTBTC': {'tick_size': 1e-08, 'lot_size': 1.0},
  'BCPTETH': {'tick_size': 1e-08, 'lot_size': 1.0},
  'BCPTBNB': {'tick_size': 1e-06, 'lot_size': 1.0},
  'ARNBTC': {'tick_size': 1e-08, 'lot_size': 1.0},
  'ARNETH': {'tick_size': 1e-08, 'lot_size': 1.0},
  'GVTBTC': {'tick_size': 1e-08, 'lot_size': 0.1},
  'GVTETH': {'tick_size': 1e-06, 'lot_size': 0.01},
  'CDTBTC': {'tick_size': 1e-08, 'lot_size': 1.0},
  'CDTETH': {'tick_size': 1e-08, 'lot_size': 1.0},
  'GXSBTC': {'tick_size': 1e-08, 'lot_size': 1.0},
  'GXSETH': {'tick_size': 1e-07, 'lot_size': 1.0},
  'NEOUSDT': {'tick_size': 0.001, 'lot_size': 0.01},
  'NEOBNB': {'tick_size': 1e-05, 'lot_size': 0.01},
  'POEBTC': {'tick_size': 1e-08, 'lot_size': 1.0},
  'POEETH': {'tick_size': 1e-08, 'lot_size': 1.0},
  'QSPBTC': {'tick_size': 1e-08, 'lot_size': 1.0},
  'QSPETH': {'tick_size': 1e-08, 'lot_size': 1.0},
  'QSPBNB': {'tick_size': 1e-07, 'lot_size': 1.0},
  'BTSBTC': {'tick_size': 1e-08, 'lot_size': 1.0},
  'BTSETH': {'tick_size': 1e-08, 'lot_size': 1.0},
  'BTSBNB': {'tick_size': 1e-06, 'lot_size': 1.0},
  'XZCBTC': {'tick_size': 1e-07, 'lot_size': 0.01},
  'XZCETH': {'tick_size': 1e-06, 'lot_size': 0.01},
  'XZCBNB': {'tick_size': 0.0001, 'lot_size': 0.01},
  'LSKBTC': {'tick_size': 1e-08, 'lot_size': 0.1},
  'LSKETH': {'tick_size': 1e-07, 'lot_size': 0.1},
  'LSKBNB': {'tick_size': 1e-05, 'lot_size': 0.1},
  'TNTBTC': {'tick_size': 1e-08, 'lot_size': 1.0},
  'TNTETH': {'tick_size': 1e-08, 'lot_size': 1.0},
  'FUELBTC': {'tick_size': 1e-08, 'lot_size': 1.0},
  'FUELETH': {'tick_size': 1e-08, 'lot_size': 1.0},
  'MANABTC': {'tick_size': 1e-08, 'lot_size': 1.0},
  'MANAETH': {'tick_size': 1e-07, 'lot_size': 1.0},
  'BCDBTC': {'tick_size': 1e-08, 'lot_size': 0.1},
  'BCDETH': {'tick_size': 1e-05, 'lot_size': 0.001},
  'DGDBTC': {'tick_size': 1e-06, 'lot_size': 0.001},
  'DGDETH': {'tick_size': 1e-05, 'lot_size': 0.001},
  'IOTABNB': {'tick_size': 1e-06, 'lot_size': 1.0},
  'ADXBTC': {'tick_size': 1e-08, 'lot_size': 1.0},
  'ADXETH': {'tick_size': 1e-08, 'lot_size': 1.0},
  'ADXBNB': {'tick_size': 1e-06, 'lot_size': 1.0},
  'ADABTC': {'tick_size': 1e-08, 'lot_size': 0.1},
  'ADAETH': {'tick_size': 1e-07, 'lot_size': 0.1},
  'PPTBTC': {'tick_size': 1e-08, 'lot_size': 0.1},
  'PPTETH': {'tick_size': 1e-06, 'lot_size': 0.01},
  'CMTBTC': {'tick_size': 1e-08, 'lot_size': 1.0},
  'CMTETH': {'tick_size': 1e-08, 'lot_size': 1.0},
  'CMTBNB': {'tick_size': 1e-06, 'lot_size': 1.0},
  'XLMBTC': {'tick_size': 1e-08, 'lot_size': 1.0},
  'XLMETH': {'tick_size': 1e-08, 'lot_size': 1.0},
  'XLMBNB': {'tick_size': 1e-07, 'lot_size': 1.0},
  'CNDBTC': {'tick_size': 1e-08, 'lot_size': 1.0},
  'CNDETH': {'tick_size': 1e-08, 'lot_size': 1.0},
  'CNDBNB': {'tick_size': 1e-07, 'lot_size': 1.0},
  'LENDBTC': {'tick_size': 1e-08, 'lot_size': 1.0},
  'LENDETH': {'tick_size': 1e-08, 'lot_size': 1.0},
  'WABIBTC': {'tick_size': 1e-08, 'lot_size': 1.0},
  'WABIETH': {'tick_size': 1e-08, 'lot_size': 1.0},
  'WABIBNB': {'tick_size': 1e-07, 'lot_size': 1.0},
  'LTCETH': {'tick_size': 1e-05, 'lot_size': 0.001},
  'LTCUSDT': {'tick_size': 0.01, 'lot_size': 0.001},
  'LTCBNB': {'tick_size': 0.0001, 'lot_size': 0.001},
  'TNBBTC': {'tick_size': 1e-08, 'lot_size': 1.0},
  'TNBETH': {'tick_size': 1e-08, 'lot_size': 1.0},
  'WAVESBTC': {'tick_size': 1e-08, 'lot_size': 0.01},
  'WAVESETH': {'tick_size': 1e-06, 'lot_size': 0.01},
  'WAVESBNB': {'tick_size': 1e-05, 'lot_size': 0.01},
  'GTOBTC': {'tick_size': 1e-08, 'lot_size': 1.0},
  'GTOETH': {'tick_size': 1e-08, 'lot_size': 1.0},
  'GTOBNB': {'tick_size': 1e-06, 'lot_size': 1.0},
  'ICXBTC': {'tick_size': 1e-08, 'lot_size': 1.0},
  'ICXETH': {'tick_size': 1e-07, 'lot_size': 1.0},
  'ICXBNB': {'tick_size': 1e-06, 'lot_size': 1.0},
  'OSTBTC': {'tick_size': 1e-08, 'lot_size': 1.0},
  'OSTETH': {'tick_size': 1e-08, 'lot_size': 1.0},
  'OSTBNB': {'tick_size': 1e-07, 'lot_size': 1.0},
  'ELFBTC': {'tick_size': 1e-08, 'lot_size': 1.0},
  'ELFETH': {'tick_size': 1e-07, 'lot_size': 1.0},
  'AIONBTC': {'tick_size': 1e-08, 'lot_size': 1.0},
  'AIONETH': {'tick_size': 1e-08, 'lot_size': 1.0},
  'AIONBNB': {'tick_size': 1e-06, 'lot_size': 1.0},
  'NEBLBTC': {'tick_size': 1e-08, 'lot_size': 0.1},
  'NEBLBNB': {'tick_size': 1e-05, 'lot_size': 0.1},
  'BRDBTC': {'tick_size': 1e-08, 'lot_size': 1.0},
  'BRDETH': {'tick_size': 1e-08, 'lot_size': 1.0},
  'BRDBNB': {'tick_size': 1e-05, 'lot_size': 0.1},
  'MCOBNB': {'tick_size': 1e-05, 'lot_size': 0.1},
  'EDOBTC': {'tick_size': 1e-08, 'lot_size': 1.0},
  'EDOETH': {'tick_size': 1e-06, 'lot_size': 0.01},
  'WINGSBTC': {'tick_size': 1e-08, 'lot_size': 1.0},
  'WINGSETH': {'tick_size': 1e-07, 'lot_size': 1.0},
  'NAVBTC': {'tick_size': 1e-08, 'lot_size': 1.0},
  'NAVETH': {'tick_size': 1e-07, 'lot_size': 1.0},
  'NAVBNB': {'tick_size': 1e-06, 'lot_size': 1.0},
  'LUNBTC': {'tick_size': 1e-07, 'lot_size': 0.01},
  'LUNETH': {'tick_size': 1e-06, 'lot_size': 0.01},
  'TRIGBTC': {'tick_size': 1e-07, 'lot_size': 0.01},
  'TRIGETH': {'tick_size': 1e-06, 'lot_size': 0.01},
  'TRIGBNB': {'tick_size': 1e-05, 'lot_size': 0.1},
  'APPCBTC': {'tick_size': 1e-08, 'lot_size': 1.0},
  'APPCETH': {'tick_size': 1e-07, 'lot_size': 1.0},
  'APPCBNB': {'tick_size': 1e-06, 'lot_size': 1.0},
  'VIBEBTC': {'tick_size': 1e-08, 'lot_size': 1.0},
  'VIBEETH': {'tick_size': 1e-07, 'lot_size': 1.0},
  'RLCBTC': {'tick_size': 1e-08, 'lot_size': 0.1},
  'RLCETH': {'tick_size': 1e-07, 'lot_size': 0.1},
  'RLCBNB': {'tick_size': 1e-05, 'lot_size': 0.1},
  'INSBTC': {'tick_size': 1e-08, 'lot_size': 1.0},
  'INSETH': {'tick_size': 1e-06, 'lot_size': 0.01},
  'PIVXBTC': {'tick_size': 1e-08, 'lot_size': 1.0},
  'PIVXBNB': {'tick_size': 1e-06, 'lot_size': 0.1},
  'IOSTBTC': {'tick_size': 1e-08, 'lot_size': 1.0},
  'IOSTETH': {'tick_size': 1e-08, 'lot_size': 1.0},
  'CHATBTC': {'tick_size': 1e-08, 'lot_size': 1.0},
  'CHATETH': {'tick_size': 1e-08, 'lot_size': 1.0},
  'STEEMBTC': {'tick_size': 1e-08, 'lot_size': 1.0},
  'STEEMETH': {'tick_size': 1e-07, 'lot_size': 1.0},
  'STEEMBNB': {'tick_size': 1e-05, 'lot_size': 0.1},
  'NANOBTC': {'tick_size': 1e-07, 'lot_size': 0.1},
  'NANOETH': {'tick_size': 1e-06, 'lot_size': 0.1},
  'NANOBNB': {'tick_size': 1e-05, 'lot_size': 0.1},
  'VIABTC': {'tick_size': 1e-08, 'lot_size': 1.0},
  'VIAETH': {'tick_size': 1e-06, 'lot_size': 0.01},
  'VIABNB': {'tick_size': 1e-05, 'lot_size': 0.1},
  'BLZBTC': {'tick_size': 1e-08, 'lot_size': 1.0},
  'BLZETH': {'tick_size': 1e-08, 'lot_size': 1.0},
  'BLZBNB': {'tick_size': 1e-07, 'lot_size': 1.0},
  'AEBTC': {'tick_size': 1e-08, 'lot_size': 1.0},
  'AEETH': {'tick_size': 1e-06, 'lot_size': 0.01},
  'AEBNB': {'tick_size': 1e-05, 'lot_size': 0.1},
  'RPXBTC': {'tick_size': 1e-08, 'lot_size': 1.0},
  'RPXETH': {'tick_size': 1e-08, 'lot_size': 1.0},
  'RPXBNB': {'tick_size': 1e-06, 'lot_size': 1.0},
  'NCASHBTC': {'tick_size': 1e-08, 'lot_size': 1.0},
  'NCASHETH': {'tick_size': 1e-08, 'lot_size': 1.0},
  'NCASHBNB': {'tick_size': 1e-07, 'lot_size': 1.0},
  'POABTC': {'tick_size': 1e-08, 'lot_size': 1.0},
  'POAETH': {'tick_size': 1e-08, 'lot_size': 1.0},
  'POABNB': {'tick_size': 1e-06, 'lot_size': 1.0},
  'ZILBTC': {'tick_size': 1e-08, 'lot_size': 1.0},
  'ZILETH': {'tick_size': 1e-08, 'lot_size': 1.0},
  'ZILBNB': {'tick_size': 1e-08, 'lot_size': 1.0},
  'ONTBTC': {'tick_size': 1e-08, 'lot_size': 1.0},
  'ONTETH': {'tick_size': 1e-07, 'lot_size': 1.0},
  'ONTBNB': {'tick_size': 1e-06, 'lot_size': 1.0},
  'STORMBTC': {'tick_size': 1e-08, 'lot_size': 1.0},
  'STORMETH': {'tick_size': 1e-08, 'lot_size': 1.0},
  'STORMBNB': {'tick_size': 1e-07, 'lot_size': 1.0},
  'QTUMBNB': {'tick_size': 1e-05, 'lot_size': 0.1},
  'QTUMUSDT': {'tick_size': 0.001, 'lot_size': 0.1},
  'XEMBTC': {'tick_size': 1e-08, 'lot_size': 1.0},
  'XEMETH': {'tick_size': 1e-08, 'lot_size': 1.0},
  'XEMBNB': {'tick_size': 1e-06, 'lot_size': 1.0},
  'WANBTC': {'tick_size': 1e-08, 'lot_size': 1.0},
  'WANETH': {'tick_size': 1e-07, 'lot_size': 1.0},
  'WANBNB': {'tick_size': 1e-06, 'lot_size': 0.1},
  'WPRBTC': {'tick_size': 1e-08, 'lot_size': 1.0},
  'WPRETH': {'tick_size': 1e-08, 'lot_size': 1.0},
  'QLCBTC': {'tick_size': 1e-08, 'lot_size': 1.0},
  'QLCETH': {'tick_size': 1e-08, 'lot_size': 1.0},
  'SYSBTC': {'tick_size': 1e-08, 'lot_size': 1.0},
  'SYSETH': {'tick_size': 1e-08, 'lot_size': 1.0},
  'SYSBNB': {'tick_size': 1e-06, 'lot_size': 1.0},
  'QLCBNB': {'tick_size': 1e-06, 'lot_size': 1.0},
  'GRSBTC': {'tick_size': 1e-08, 'lot_size': 1.0},
  'GRSETH': {'tick_size': 1e-08, 'lot_size': 1.0},
  'ADAUSDT': {'tick_size': 0.0001, 'lot_size': 0.1},
  'ADABNB': {'tick_size': 1e-06, 'lot_size': 0.1},
  'CLOAKBTC': {'tick_size': 1e-07, 'lot_size': 0.01},
  'CLOAKETH': {'tick_size': 1e-06, 'lot_size': 0.01},
  'GNTBTC': {'tick_size': 1e-08, 'lot_size': 1.0},
  'GNTETH': {'tick_size': 1e-08, 'lot_size': 1.0},
  'GNTBNB': {'tick_size': 1e-06, 'lot_size': 1.0},
  'LOOMBTC': {'tick_size': 1e-08, 'lot_size': 1.0},
  'LOOMETH': {'tick_size': 1e-08, 'lot_size': 1.0},
  'LOOMBNB': {'tick_size': 1e-06, 'lot_size': 1.0},
  'XRPUSDT': {'tick_size': 0.0001, 'lot_size': 0.1},
  'BCNBTC': {'tick_size': 1e-08, 'lot_size': 1.0},
  'BCNETH': {'tick_size': 1e-08, 'lot_size': 1.0},
  'BCNBNB': {'tick_size': 1e-06, 'lot_size': 1.0},
  'REPBTC': {'tick_size': 1e-07, 'lot_size': 0.01},
  'REPBNB': {'tick_size': 0.0001, 'lot_size': 0.01},
  'BTCTUSD': {'tick_size': 0.01, 'lot_size': 1e-05},
  'TUSDBTC': {'tick_size': 1e-08, 'lot_size': 1.0},
  'ETHTUSD': {'tick_size': 0.01, 'lot_size': 0.0001},
  'TUSDETH': {'tick_size': 1e-08, 'lot_size': 1.0},
  'TUSDBNB': {'tick_size': 1e-05, 'lot_size': 0.1},
  'ZENBTC': {'tick_size': 1e-08, 'lot_size': 0.01},
  'ZENETH': {'tick_size': 1e-06, 'lot_size': 0.01},
  'ZENBNB': {'tick_size': 0.0001, 'lot_size': 0.01},
  'SKYCOINBTC': {'tick_size': 1e-08, 'lot_size': 0.1},
  'SKYCOINETH': {'tick_size': 1e-05, 'lot_size': 0.001},
  'SKYCOINBNB': {'tick_size': 1e-05, 'lot_size': 0.1},
  'EOSUSDT': {'tick_size': 0.0001, 'lot_size': 0.1},
  'EOSBNB': {'tick_size': 1e-06, 'lot_size': 0.1},
  'CVCBTC': {'tick_size': 1e-08, 'lot_size': 1.0},
  'CVCETH': {'tick_size': 1e-07, 'lot_size': 1.0},
  'CVCBNB': {'tick_size': 1e-06, 'lot_size': 1.0},
  'THETABTC': {'tick_size': 1e-08, 'lot_size': 0.1},
  'THETAETH': {'tick_size': 1e-07, 'lot_size': 0.1},
  'THETABNB': {'tick_size': 1e-06, 'lot_size': 0.1},
  'XRPBNB': {'tick_size': 1e-07, 'lot_size': 0.1},
  'TUSDUSDT': {'tick_size': 0.0001, 'lot_size': 1.0},
  'IOTAUSDT': {'tick_size': 0.0001, 'lot_size': 1.0},
  'XLMUSDT': {'tick_size': 0.0001, 'lot_size': 1.0},
  'IOTXBTC': {'tick_size': 1e-08, 'lot_size': 1.0},
  'IOTXETH': {'tick_size': 1e-08, 'lot_size': 1.0},
  'QKCBTC': {'tick_size': 1e-08, 'lot_size': 1.0},
  'QKCETH': {'tick_size': 1e-08, 'lot_size': 1.0},
  'AGIBTC': {'tick_size': 1e-08, 'lot_size': 1.0},
  'AGIETH': {'tick_size': 1e-08, 'lot_size': 1.0},
  'AGIBNB': {'tick_size': 1e-06, 'lot_size': 1.0},
  'NXSBTC': {'tick_size': 1e-08, 'lot_size': 1.0},
  'NXSETH': {'tick_size': 1e-06, 'lot_size': 0.01},
  'NXSBNB': {'tick_size': 1e-05, 'lot_size': 0.1},
  'ENJBNB': {'tick_size': 1e-06, 'lot_size': 0.1},
  'DATABTC': {'tick_size': 1e-08, 'lot_size': 1.0},
  'DATAETH': {'tick_size': 1e-08, 'lot_size': 1.0},
  'ONTUSDT': {'tick_size': 0.0001, 'lot_size': 1.0},
  'TRXBNB': {'tick_size': 1e-07, 'lot_size': 1.0},
  'TRXUSDT': {'tick_size': 0.0001, 'lot_size': 0.1},
  'ETCUSDT': {'tick_size': 0.01, 'lot_size': 0.01},
  'ETCBNB': {'tick_size': 1e-05, 'lot_size': 0.01},
  'ICXUSDT': {'tick_size': 0.0001, 'lot_size': 0.1},
  'SCBTC': {'tick_size': 1e-08, 'lot_size': 1.0},
  'SCETH': {'tick_size': 1e-08, 'lot_size': 1.0},
  'NPXSBTC': {'tick_size': 1e-08, 'lot_size': 1.0},
  'NPXSETH': {'tick_size': 1e-08, 'lot_size': 1.0},
  'VENUSDT': {'tick_size': 0.0001, 'lot_size': 0.01},
  'KEYBTC': {'tick_size': 1e-08, 'lot_size': 1.0},
  'KEYETH': {'tick_size': 1e-08, 'lot_size': 1.0},
  'NASBTC': {'tick_size': 1e-08, 'lot_size': 1.0},
  'NASETH': {'tick_size': 1e-08, 'lot_size': 1.0},
  'NASBNB': {'tick_size': 1e-05, 'lot_size': 0.1},
  'MFTBTC': {'tick_size': 1e-08, 'lot_size': 1.0},
  'MFTETH': {'tick_size': 1e-08, 'lot_size': 1.0},
  'MFTBNB': {'tick_size': 1e-08, 'lot_size': 1.0},
  'DENTBTC': {'tick_size': 1e-08, 'lot_size': 1.0},
  'DENTETH': {'tick_size': 1e-08, 'lot_size': 1.0},
  'ARDRBTC': {'tick_size': 1e-08, 'lot_size': 1.0},
  'ARDRETH': {'tick_size': 1e-08, 'lot_size': 1.0},
  'ARDRBNB': {'tick_size': 1e-06, 'lot_size': 1.0},
  'NULSUSDT': {'tick_size': 0.0001, 'lot_size': 1.0},
  'HOTBTC': {'tick_size': 1e-08, 'lot_size': 1.0},
  'HOTETH': {'tick_size': 1e-08, 'lot_size': 1.0},
  'VETBTC': {'tick_size': 1e-08, 'lot_size': 1.0},
  'VETETH': {'tick_size': 1e-08, 'lot_size': 1.0},
  'VETUSDT': {'tick_size': 1e-05, 'lot_size': 0.1},
  'VETBNB': {'tick_size': 1e-08, 'lot_size': 1.0},
  'DOCKBTC': {'tick_size': 1e-08, 'lot_size': 1.0},
  'DOCKETH': {'tick_size': 1e-08, 'lot_size': 1.0},
  'POLYBTC': {'tick_size': 1e-08, 'lot_size': 1.0},
  'POLYBNB': {'tick_size': 1e-06, 'lot_size': 1.0},
  'PHXBTC': {'tick_size': 1e-08, 'lot_size': 1.0},
  'PHXETH': {'tick_size': 1e-08, 'lot_size': 1.0},
  'PHXBNB': {'tick_size': 1e-06, 'lot_size': 1.0},

In [5]:
import pandas as pd

df = pd.read_parquet("/data/sigma/zzy/janus/results/algo_v5_live_new_02/pred_vol_train_7_adjusted_mean/20260101_20260311/20260401_031206/1000SHIBUSDT/2026-01-01_market_data.parquet")
df

,timestamp,best_bid,best_ask,mid_price,micro_price,best_bid_qty,best_ask_qty,forecast_mid_price,bid_price,ask_price,...,mid_price_tick,mid_price_chg,order_qty,skew,bid_depth_tick,ask_depth_tick,bid_price_before_align,ask_price_before_align,final_bid,final_ask
0,1767225600062000000,0.006906,0.006907,0.006906,0.006907,1969966.0,49661.0,0.006907,NaN,NaN,...,0.0,NaN,1448.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN
1,1767225600082000000,0.006906,0.006907,0.006906,0.006907,1969966.0,49661.0,0.006907,NaN,NaN,...,0.0,0.0,1448.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN
2,1767225600102000000,0.006906,0.006907,0.006906,0.006907,1969966.0,49661.0,0.006907,NaN,NaN,...,0.0,0.0,1448.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN
3,1767225600122000000,0.006906,0.006907,0.006906,0.006907,1969966.0,49661.0,0.006907,NaN,NaN,...,0.0,0.0,1448.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN
4,1767225600142000000,0.006906,0.006907,0.006906,0.006907,1969966.0,49661.0,0.006907,NaN,NaN,...,0.0,0.0,1448.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4319992,1767311999902000000,0.007462,0.007463,0.007463,0.007462,53754.0,2689944.0,0.007462,NaN,NaN,...,0.0,0.0,1340.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN
4319993,1767311999922000000,0.007462,0.007463,0.007463,0.007462,69790.0,2689944.0,0.007462,NaN,NaN,...,0.0,0.0,1340.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN
4319994,1767311999942000000,0.007462,0.007463,0.007463,0.007462,69790.0,2689944.0,0.007462,NaN,NaN,...,0.0,0.0,1340.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN
4319995,1767311999962000000,0.007462,0.007463,0.007463,0.007462,69790.0,2689944.0,0.007462,NaN,NaN,...,0.0,0.0,1340.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN
4319996,1767311999982000000,0.007462,0.007463,0.007463,0.007462,69790.0,2689944.0,0.007462,NaN,NaN,...,0.0,0.0,1340.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
import pandas as pd

df = pd.read_parquet("/data/sigma/zzy/janus/results/vol_pred_prod/features/XRPUSDT/2026-01-01/features_label.parquet")
df

,timestamp,vol_1m,vol_3m,vol_5m,vol_10m,vol_15m,vol_30m,vol_60m,vol_120m,vol_ratio_1m_3m,...,vol_ratio_15m_60m,vol_ratio_15m_120m,vol_ratio_30m_60m,vol_ratio_30m_120m,vol_ratio_60m_120m,hour,minute,tod_sin,tod_cos,y_vol_5m
0,1767225600000000000,0.057745,0.063239,0.062718,0.067701,0.073712,0.072840,0.080709,0.100499,0.913113,...,0.913306,0.733460,0.902498,0.724780,0.803082,0.0,0.0,0.000000,1.000000,0.085832
1,1767225600020000000,0.057745,0.063239,0.062718,0.067701,0.073712,0.072840,0.080709,0.100499,0.913113,...,0.913306,0.733460,0.902498,0.724780,0.803082,0.0,0.0,0.000000,1.000000,0.085832
2,1767225600040000000,0.057745,0.063239,0.060554,0.067701,0.073712,0.072840,0.080709,0.100499,0.913113,...,0.913306,0.733460,0.902498,0.724780,0.803082,0.0,0.0,0.000000,1.000000,0.085832
3,1767225600060000000,0.057745,0.063239,0.060554,0.067701,0.073712,0.072840,0.080709,0.100499,0.913113,...,0.913306,0.733460,0.902498,0.724780,0.803082,0.0,0.0,0.000000,1.000000,0.085832
4,1767225600080000000,0.057745,0.063239,0.060554,0.067701,0.073712,0.072840,0.080709,0.100499,0.913113,...,0.913306,0.733460,0.902498,0.724780,0.803082,0.0,0.0,0.000000,1.000000,0.085832
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4304995,1767311699900000000,0.031626,0.045949,0.064805,0.071531,0.077603,0.075866,0.090646,0.081777,0.688287,...,0.856118,0.948965,0.836947,0.927716,1.108452,23.0,54.0,-0.026177,0.999657,0.083066
4304996,1767311699920000000,0.031626,0.045949,0.064805,0.071531,0.077603,0.075866,0.090646,0.081777,0.688287,...,0.856118,0.948965,0.836947,0.927716,1.108452,23.0,54.0,-0.026177,0.999657,0.083066
4304997,1767311699940000000,0.031626,0.045949,0.064805,0.071531,0.077603,0.075866,0.090646,0.081777,0.688287,...,0.856118,0.948965,0.836947,0.927716,1.108452,23.0,54.0,-0.026177,0.999657,0.083066
4304998,1767311699960000000,0.031626,0.045949,0.064805,0.071531,0.077603,0.075866,0.090646,0.081777,0.688287,...,0.856118,0.948965,0.836947,0.927716,1.108452,23.0,54.0,-0.026177,0.999657,0.083066
4304999,1767311699980000000,0.031626,0.045949,0.064805,0.071531,0.077603,0.075866,0.090646,0.081777,0.688287,...,0.856118,0.948965,0.836947,0.927716,1.108452,23.0,54.0,-0.026177,0.999657,0.083066

In [11]:
df["vol_10m"].describe()

count    4.305000e+06
mean     8.196357e-02
std      2.924632e-02
min      3.316678e-02
25%      6.258258e-02
50%      7.393571e-02
75%      9.530503e-02
max      2.329869e-01
Name: vol_10m, dtype: float64

In [12]:
8.196357e-02

0.08196357

In [14]:
import numpy as np
0.08196357 * np.sqrt(50)

0.5795699615725828

In [2]:
df.columns

Index(['timestamp', 'vol_1m', 'vol_3m', 'vol_5m', 'vol_10m', 'vol_15m',
       'vol_30m', 'vol_60m', 'vol_120m', 'vol_ratio_1m_3m', 'vol_ratio_1m_5m',
       'vol_ratio_1m_10m', 'vol_ratio_1m_15m', 'vol_ratio_1m_30m',
       'vol_ratio_1m_60m', 'vol_ratio_1m_120m', 'vol_ratio_3m_5m',
       'vol_ratio_3m_10m', 'vol_ratio_3m_15m', 'vol_ratio_3m_30m',
       'vol_ratio_3m_60m', 'vol_ratio_3m_120m', 'vol_ratio_5m_10m',
       'vol_ratio_5m_15m', 'vol_ratio_5m_30m', 'vol_ratio_5m_60m',
       'vol_ratio_5m_120m', 'vol_ratio_10m_15m', 'vol_ratio_10m_30m',
       'vol_ratio_10m_60m', 'vol_ratio_10m_120m', 'vol_ratio_15m_30m',
       'vol_ratio_15m_60m', 'vol_ratio_15m_120m', 'vol_ratio_30m_60m',
       'vol_ratio_30m_120m', 'vol_ratio_60m_120m', 'hour', 'minute', 'tod_sin',
       'tod_cos', 'y_vol_5m'],
      dtype='object')

In [3]:
len(df.columns)

42

### 验证历史训练和预测结果

In [13]:
import pandas as pd
df = pd.read_parquet("/data/sigma/zzy/janus/results/vol_pred_prod/results/2026-01-01/XRPUSDT/results.parquet")
df

                   timestamp    y_true        y_pred
0        1767225600000000000  0.085832  1.067839e+07
1        1767225600020000000  0.085832  1.067839e+07
2        1767225600040000000  0.085832  1.067839e+07
3        1767225600060000000  0.085832  1.067839e+07
4        1767225600080000000  0.085832  1.067839e+07
...                      ...       ...           ...
4304995  1767311699900000000  0.083066  7.999597e+06
4304996  1767311699920000000  0.083066  7.999597e+06
4304997  1767311699940000000  0.083066  7.999597e+06
4304998  1767311699960000000  0.083066  7.999597e+06
4304999  1767311699980000000  0.083066  7.999597e+06

[4305000 rows x 3 columns]

In [6]:
import pandas as pd
df = pd.read_parquet("/data/sigma/zzy/janus/results/vol_pred_prod/features/XRPUSDT/2026-01-01/features_label.parquet")
df

,timestamp,vol_1m,vol_3m,vol_5m,vol_10m,vol_15m,vol_30m,vol_60m,vol_120m,vol_ratio_1m_3m,...,vol_ratio_15m_60m,vol_ratio_15m_120m,vol_ratio_30m_60m,vol_ratio_30m_120m,vol_ratio_60m_120m,hour,minute,tod_sin,tod_cos,y_vol_5m
0,1767225600000000000,4.697066e+06,9.488136e+06,7.844383e+06,8.605416e+06,9.205657e+06,8.577196e+06,9.371229e+06,1.121537e+07,0.495046,...,0.982332,0.820807,0.915269,0.764771,0.835570,0.0,0.0,0.000000,1.000000,1.023540e+07
1,1767225600020000000,4.697066e+06,9.488136e+06,7.844383e+06,8.605400e+06,9.205657e+06,8.577196e+06,9.371229e+06,1.121537e+07,0.495046,...,0.982332,0.820807,0.915269,0.764771,0.835570,0.0,0.0,0.000000,1.000000,1.023540e+07
2,1767225600040000000,4.697066e+06,9.488136e+06,7.761693e+06,8.605400e+06,9.205657e+06,8.577194e+06,9.371229e+06,1.121537e+07,0.495046,...,0.982332,0.820807,0.915269,0.764771,0.835570,0.0,0.0,0.000000,1.000000,1.023540e+07
3,1767225600060000000,4.697066e+06,9.488136e+06,7.761693e+06,8.605400e+06,9.205657e+06,8.577194e+06,9.371229e+06,1.121537e+07,0.495046,...,0.982332,0.820807,0.915269,0.764771,0.835570,0.0,0.0,0.000000,1.000000,1.023540e+07
4,1767225600080000000,4.697066e+06,9.488136e+06,7.761693e+06,8.605400e+06,9.205657e+06,8.574100e+06,9.371229e+06,1.121537e+07,0.495046,...,0.982332,0.820807,0.914939,0.764495,0.835570,0.0,0.0,0.000000,1.000000,1.023540e+07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4304995,1767311699900000000,9.964545e+06,9.314651e+06,1.032244e+07,1.301145e+07,1.495154e+07,1.530429e+07,1.768849e+07,1.399780e+07,1.069771,...,0.845269,1.068135,0.865212,1.093336,1.263663,23.0,54.0,-0.026177,0.999657,1.862297e+07
4304996,1767311699920000000,9.964545e+06,9.314651e+06,1.032244e+07,1.301145e+07,1.495154e+07,1.530429e+07,1.768849e+07,1.399780e+07,1.069771,...,0.845269,1.068135,0.865212,1.093336,1.263663,23.0,54.0,-0.026177,0.999657,1.862297e+07
4304997,1767311699940000000,9.964545e+06,9.314651e+06,1.032244e+07,1.301145e+07,1.495154e+07,1.530429e+07,1.768849e+07,1.399780e+07,1.069771,...,0.845269,1.068135,0.865212,1.093336,1.263663,23.0,54.0,-0.026177,0.999657,1.862297e+07
4304998,1767311699960000000,9.964709e+06,9.314709e+06,1.032248e+07,1.301147e+07,1.495154e+07,1.530429e+07,1.768850e+07,1.399780e+07,1.069782,...,0.845269,1.068136,0.865212,1.093336,1.263663,23.0,54.0,-0.026177,0.999657,1.862295e+07
4304999,1767311699980000000,9.964709e+06,9.314709e+06,1.032248e+07,1.301147e+07,1.495154e+07,1.530427e+07,1.768850e+07,1.399780e+07,1.069782,...,0.845269,1.068136,0.865211,1.093334,1.263663,23.0,54.0,-0.026177,0.999657,1.862307e+07

In [7]:
import pandas as pd
df = pd.read_parquet("/data/sigma/zzy/janus/results/vol_pred_prod/features/XRPUSDT/2026-01-02/features_label.parquet")
df

,timestamp,vol_1m,vol_3m,vol_5m,vol_10m,vol_15m,vol_30m,vol_60m,vol_120m,vol_ratio_1m_3m,...,vol_ratio_15m_60m,vol_ratio_15m_120m,vol_ratio_30m_60m,vol_ratio_30m_120m,vol_ratio_60m_120m,hour,minute,tod_sin,tod_cos,y_vol_5m
0,1767312000000000000,2.669038e+07,1.705513e+07,1.862307e+07,1.505585e+07,1.511508e+07,1.592964e+07,1.840173e+07,1.444396e+07,1.564947,...,0.821394,1.046464,0.865660,1.102859,1.274009,0.0,0.0,0.000000,1.000000,2.449130e+07
1,1767312000020000000,2.669038e+07,1.705513e+07,1.862307e+07,1.505585e+07,1.511508e+07,1.592961e+07,1.840173e+07,1.444396e+07,1.564947,...,0.821394,1.046464,0.865658,1.102856,1.274009,0.0,0.0,0.000000,1.000000,2.449130e+07
2,1767312000040000000,2.669038e+07,1.705506e+07,1.862307e+07,1.505539e+07,1.511508e+07,1.592961e+07,1.840173e+07,1.444396e+07,1.564954,...,0.821394,1.046464,0.865658,1.102856,1.274009,0.0,0.0,0.000000,1.000000,2.449130e+07
3,1767312000060000000,2.669066e+07,1.705520e+07,1.862315e+07,1.505544e+07,1.511199e+07,1.592963e+07,1.840174e+07,1.444396e+07,1.564957,...,0.821226,1.046250,0.865659,1.102857,1.274009,0.0,0.0,0.000000,1.000000,2.449124e+07
4,1767312000080000000,2.669066e+07,1.705520e+07,1.862315e+07,1.505544e+07,1.511199e+07,1.592963e+07,1.840174e+07,1.444396e+07,1.564957,...,0.821226,1.046250,0.865659,1.102857,1.274009,0.0,0.0,0.000000,1.000000,2.449124e+07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4304995,1767398099900000000,7.019599e+06,8.396524e+06,7.615535e+06,9.227472e+06,9.264498e+06,1.248527e+07,1.330183e+07,1.378589e+07,0.836013,...,0.696483,0.672028,0.938613,0.905656,0.964888,23.0,54.0,-0.026177,0.999657,8.313833e+06
4304996,1767398099920000000,7.019599e+06,8.396524e+06,7.615535e+06,9.227472e+06,9.264498e+06,1.246234e+07,1.330183e+07,1.378589e+07,0.836013,...,0.696483,0.672028,0.936889,0.903993,0.964888,23.0,54.0,-0.026177,0.999657,8.313833e+06
4304997,1767398099940000000,7.019599e+06,8.396524e+06,7.615535e+06,9.227472e+06,9.264498e+06,1.246233e+07,1.330183e+07,1.378589e+07,0.836013,...,0.696483,0.672028,0.936888,0.903992,0.964888,23.0,54.0,-0.026177,0.999657,8.313833e+06
4304998,1767398099960000000,7.019599e+06,8.396524e+06,7.615530e+06,9.227472e+06,9.264498e+06,1.245473e+07,1.330183e+07,1.378589e+07,0.836013,...,0.696483,0.672028,0.936317,0.903441,0.964888,23.0,54.0,-0.026177,0.999657,8.313833e+06
4304999,1767398099980000000,7.019599e+06,8.396524e+06,7.615530e+06,9.227472e+06,9.264498e+06,1.245443e+07,1.330183e+07,1.378589e+07,0.836013,...,0.696483,0.672028,0.936294,0.903419,0.964888,23.0,54.0,-0.026177,0.999657,8.313840e+06

In [9]:
import numpy as np
data = np.load("/data/sigma/zzy/janus/results/vol_pred_prod/results/2026-01-01/XRPUSDT/results.npz")["data"]
print(data.shape)
data

(4305000,)

array([(1767225600000000000, 10235398.08425283, 11247351.19488757),
       (1767225600020000000, 10235398.92627174, 11247351.19488757),
       (1767225600040000000, 10235398.92627174, 11247351.19488757), ...,
       (1767311699940000000, 18622970.21969336, 10952241.77982409),
       (1767311699960000000, 18622951.85959752, 10952241.77982409),
       (1767311699980000000, 18623069.23886097, 10952241.77982409)],
      dtype=[('timestamp', '<i8'), ('y_true', '<f8'), ('y_pred', '<f8')])

In [24]:
import numpy as np
data = np.load("/data/sigma/zzy/janus/results/vol_pred_prod/results/2025-01-11/XRPUSDT/results.npz")["data"]
print(data.shape)
data

(4305000,)

array([(1736553600000000000, 0.30513047, 0.18141027),
       (1736553600020000000, 0.30513047, 0.18141027),
       (1736553600040000000, 0.30513047, 0.18141027), ...,
       (1736639699940000000, 0.31188644, 0.31132875),
       (1736639699960000000, 0.31188644, 0.31132875),
       (1736639699980000000, 0.31188644, 0.31132875)],
      dtype=[('timestamp', '<i8'), ('y_true', '<f8'), ('y_pred', '<f8')])

In [25]:
import numpy as np
(data["y_pred"]*np.sqrt(50)).mean()

2.099539544724706

In [36]:
import pandas as pd
df = pd.read_parquet("/data/sigma/zzy/janus/results/algo_v4_live_half_spread_2/20ms_vol_to_half_spread_5_vol_to_half_spread_grid_7_risk_adverse_queue_model/20250101_20260302/20260305_020424/XRPUSDT/2025-01-10_market_data.parquet")
df

,timestamp,best_bid,best_ask,mid_price,micro_price,best_bid_qty,best_ask_qty,forecast_mid_price,bid_price,ask_price,...,mid_price_tick,mid_price_chg,order_qty,skew,bid_depth_tick,ask_depth_tick,bid_price_before_align,ask_price_before_align,final_bid,final_ask
0,0,0.000,0.0000,0.00000,0.000000,0.0,0.0,0.000000,0.00,0.0000,...,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.00,0.0000
1,1736467200026000000,2.271,2.2711,2.27105,2.271051,11721.6,11157.0,2.271051,NaN,NaN,...,0.0,NaN,4.4,1.0,NaN,NaN,NaN,NaN,NaN,NaN
2,1736467200046000000,2.271,2.2711,2.27105,2.271051,11721.6,11157.0,2.271051,NaN,NaN,...,0.0,0.0,4.4,1.0,NaN,NaN,NaN,NaN,NaN,NaN
3,1736467200066000000,2.271,2.2711,2.27105,2.271051,11721.6,11157.0,2.271051,NaN,NaN,...,0.0,0.0,4.4,1.0,NaN,NaN,NaN,NaN,NaN,NaN
4,1736467200086000000,2.271,2.2711,2.27105,2.271051,11721.6,11157.0,2.271051,NaN,NaN,...,0.0,0.0,4.4,1.0,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4319995,1736553599906000000,2.341,2.3411,2.34105,2.341082,23773.3,5306.6,2.341082,2.34,2.3416,...,0.0,0.0,4.3,1.0,6.987248,5.068135,2.340383,2.341589,2.34,2.3416
4319996,1736553599926000000,2.341,2.3411,2.34105,2.341082,23773.3,5306.6,2.341082,2.34,2.3416,...,0.0,0.0,4.3,1.0,6.987248,5.068135,2.340383,2.341589,2.34,2.3416
4319997,1736553599946000000,2.341,2.3411,2.34105,2.341082,23773.3,5306.6,2.341082,2.34,2.3416,...,0.0,0.0,4.3,1.0,6.987248,5.068135,2.340383,2.341589,2.34,2.3416
4319998,1736553599966000000,2.341,2.3411,2.34105,2.341082,23773.3,5306.6,2.341082,2.34,2.3416,...,0.0,0.0,4.3,1.0,6.987248,5.068135,2.340383,2.341589,2.34,2.3416
4319999,1736553599986000000,2.341,2.3411,2.34105,2.341082,23773.3,5306.6,2.341082,2.34,2.3416,...,0.0,0.0,4.3,1.0,6.987248,5.068135,2.340383,2.341589,2.34,2.3416

In [37]:
df["volatility"]

0          0.000000
1               NaN
2               NaN
3               NaN
4               NaN
             ...
4319995    1.205538
4319996    1.205538
4319997    1.205538
4319998    1.205538
4319999    1.205538
Name: volatility, Length: 4320000, dtype: float64

In [38]:
df["volatility"].describe()

count    4.290001e+06
mean     2.011233e+00
std      1.392315e+00
min      0.000000e+00
25%      1.382574e+00
50%      1.712877e+00
75%      2.128369e+00
max      1.631434e+01
Name: volatility, dtype: float64

In [39]:
2.011233e+00

2.011233

In [15]:
import pandas as pd
df = pd.read_parquet("/data/sigma/zzy/janus/results/vol_pred_prod/results/2026-01-01/XRPUSDT/feature_importance.parquet")
df

               feature  importance_gain  importance_split
0              vol_30m     9.043193e+07               320
1              vol_15m     3.364416e+07               189
2              vol_10m     2.342983e+07               170
3              tod_cos     1.113188e+07               616
4               minute     9.673606e+06               517
5              tod_sin     9.019849e+06               523
6               vol_3m     8.542421e+06                91
7               vol_5m     7.836790e+06                78
8              vol_60m     7.290873e+06               292
9             vol_120m     6.668062e+06               438
10  vol_ratio_60m_120m     5.675355e+06               375
11  vol_ratio_30m_120m     4.999238e+06               265
12                hour     4.753076e+06               231
13              vol_1m     4.527707e+06                72
14   vol_ratio_30m_60m     2.795440e+06               212
15   vol_ratio_10m_15m     1.700848e+06               122
16   vol_ratio_15m_30m     1.623565e+06               137
17   vol_ratio_15m_60m     1.500217e+06               101
18    vol_ratio_5m_15m     1.463519e+06                93
19   vol_ratio_10m_30m     1.403441e+06                93
20  vol_ratio_15m_120m     1.400660e+06               106
21  vol_ratio_10m_120m     1.202516e+06                94
22   vol_ratio_10m_60m     1.094997e+06                96
23   vol_ratio_5m_120m     9.675118e+05                62
24    vol_ratio_5m_30m     7.259526e+05                64
25    vol_ratio_5m_60m     7.161290e+05                59
26   vol_ratio_3m_120m     4.785251e+05                27
27    vol_ratio_3m_60m     4.552422e+05                28
28    vol_ratio_5m_10m     4.092305e+05                45
29    vol_ratio_3m_30m     3.018694e+05                27
30    vol_ratio_3m_10m     2.511424e+05                23
31    vol_ratio_3m_15m     2.281048e+05                24
32     vol_ratio_3m_5m     2.107096e+05                19
33   vol_ratio_1m_120m     1.941148e+05                13
34    vol_ratio_1m_10m     1.702254e+05                 7
35     vol_ratio_1m_5m     1.489687e+05                11
36    vol_ratio_1m_15m     1.257231e+05                10
37    vol_ratio_1m_30m     1.108334e+05                10
38     vol_ratio_1m_3m     5.879802e+04                 9
39    vol_ratio_1m_60m     2.572900e+03                 1

In [14]:
import joblib

qt = joblib.load("/data/sigma/zzy/janus/results/vol_pred_prod/results/2026-01-01/XRPUSDT/quantile_transformer.pkl")
qt

/opt/anaconda3/lib/python3.12/site-packages/sklearn/base.py:376: InconsistentVersionWarning: Trying to unpickle estimator QuantileTransformer from version 1.8.0 when using version 1.5.1. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(

QuantileTransformer(output_distribution='normal', random_state=42)

In [16]:
file_path = "/data/sigma/zzy/janus/results/vol_pred_prod/results/2026-01-01/XRPUSDT/model.txt"

with open(file_path, "r", encoding="utf-8") as f:
    model_txt = f.read()

model_txt

'tree\nversion=v4\nnum_class=1\nnum_tree_per_iteration=1\nlabel_index=0\nmax_feature_idx=39\nobjective=regression\nfeature_names=Column_0 Column_1 Column_2 Column_3 Column_4 Column_5 Column_6 Column_7 Column_8 Column_9 Column_10 Column_11 Column_12 Column_13 Column_14 Column_15 Column_16 Column_17 Column_18 Column_19 Column_20 Column_21 Column_22 Column_23 Column_24 Column_25 Column_26 Column_27 Column_28 Column_29 Column_30 Column_31 Column_32 Column_33 Column_34 Column_35 Column_36 Column_37 Column_38 Column_39\nfeature_infos=[347530.32040630555:369703259.70634425] [1078566.2131603335:252759606.74762544] [1489507.3955151569:208066651.88078469] [2559122.7246121857:160574389.34478593] [2617426.6629795465:140983279.96938711] [4976325.3570813974:108272948.11731301] [5833938.0141305029:89014095.541601077] [6086956.2529575136:65681529.962949164] [0.052791519095073354:1.7293800719113195] [0.041640431157896195:2.2253245999845004] [0.038169338101434178:3.1296072601827611] [0.040880983960194364:3.8232648202645345] [0.019353392170381501:4.9345264986387853] [0.013529055333369943:6.3019288655370547] [0.0095220845090266577:7.8086975979576749] [0.0900295920954573:1.2906356760060742] [0.052176441614605475:1.8217087416091453] [0.063665976699004451:2.2289570265738248] [0.049031225954362219:3.0406219765102973] [0.038190275266158306:4.1212071065161915] [0.024275819016829493:5.4756162610965617] [0.079134161098717778:1.4118043926973873] [0.096521275596437611:1.7273465527307781] [0.071440372602205246:2.3714070048952789] [0.072625590932208856:3.2140399741249817] [0.046105825782896036:4.2669466762408339] [0.10801699044222493:1.2236771289736454] [0.10343035883797157:1.6937500169082216] [0.10188448796764527:2.3002977116626733] [0.091238340540989921:3.0586368295616695] [0.1550330267000726:1.4100272379533929] [0.11405148314614535:1.8961748668797456] [0.093913715769217393:2.529988752711001] [0.13272120903458037:1.3985124809398659] [0.1331567334460208:1.9310865328725757] [0.15184514875181412:1.4009477815308016] [0:23] [0:59] [-1:1] [-1:1]\ntree_sizes=6655 6641 6656 6664 6703 6678 6674 6685 6705 6710 6681 6691 6708 6682 6696 6753 6689 6672 6671 6667 6662 6748 6734 6701 6652 6663 6733 6756 6693 6774 6693 6746 6685 6705 6695 6678 6699 6720 6689 6642 6741 6681 6693 6722 6697 6624 6688 6711 6657 6707 6641 6621 6695 6618 6648 6638 6730 6633 6640 6699 6778 6715 6696 6556 6743 6661 6616 6670 6678 6637 6664 6614 6667 6644 6713 6643 6575 6586 6592 6595 6629 6656 6553 6518 6639 6537 6639 6627 6537 6550\n\nTree=0\nnum_leaves=64\nnum_cat=0\nsplit_feature=5 3 4 1 4 3 6 35 39 1 37 31 4 37 22 34 1 7 4 37 38 20 7 23 37 34 38 35 38 38 38 39 35 3 39 34 7 37 38 14 31 1 16 34 6 7 37 38 39 39 38 39 25 2 6 28 20 31 38 5 38 35 2\nsplit_gain=1.03469e+07 2.19311e+06 1.59517e+06 510736 380345 283710 176876 150764 138337 138139 120799 129578 109142 105605 102324 98502.5 92583.3 92056.9 81457.8 81106.6 75103 81133.7 72273.3 68079.4 67038.3 66884.7 60491 59040.7 56038.6 55465.3 52981.7 49179.4 46714.4 46112.9 44696 44295.3 43939.2 43387.9 42287.3 40956.1 40291.2 39465.1 43299.1 39273 37553.4 36646 36478 55860.5 34925.5 34741.5 33880.2 32432.4 32070.3 30251.3 29067.7 28926.4 28168 25930.8 25650.3 25552.5 25349.8 24658.9 24136.2\nthreshold=14416946.736946179 20161130.627111416 9056328.644662844 27339675.977263708 11616213.317655139 14958999.809582122 7111440.8723937143 1.36061291017051 0.30278504926614203 18195779.816106699 22.500000000000004 0.58172637837035746 29681018.509022847 3.5000000000000004 0.5936690787973119 1.2979714412389571 14976308.95729433 14485972.534425847 19087489.874531139 56.500000000000007 -0.53913703985740902 0.2692458174934057 7803394.1269464865 0.42214494160175658 57.500000000000007 1.1113785898379127 0.93894197835419635 1.1909959654928794 -0.44032991850403919 -0.16289508573225173 -0.96759678964602525 -0.97185599510546894 1.2231756603347819 11665058.256763408 0.9366721892483979 1.3215416770802719 65566730.447870187 16.500000000000004 -0.90538146624550897 0.43152787535369858 1.3777198692592083 39169511.292539604 0.56715328136696941 1.6751872954107829 16571598.244283671 14742305.589787351 5.5000000000000009 -0.8819191655321561 -0.35836794954530043 -0.61393937768005358 0.87142585150634855 -0.071932481969762388 0.46867344478682471 11838688.014355185 16134229.221433582 1.4901579131821665 3.0107239090281404 0.9823127223213507 -0.091501618663402048 39748544.390745215 0.55011510741598613 1.0768860994777485 22969522.509737436\ndecision_type=2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2\nleft_child=2 5 6 20 13 7 26 15 25 17 11 -10 -5 30 34 31 44 35 -18 22 21 43 -15 -23 27 38 -1 -16 -17 -19 -4 -2 -11 -33 -12 46 41 -28 51 58 -9 42 -14 -3 -7 -41 47 -6 55 -48 60 -8 -26 -31 -30 -25 59 -50 -24 -43 -13 -35 -22\nright_child=1 3 4 12 9 16 8 40 10 32 14 50 36 19 24 28 18 29 -20 -21 62 23 39 48 52 -27 37 -29 54 53 -32 33 -34 61 -36 -37 -38 -39 -40 45 -42 56 -44 -45 -46 -47 49 -49 57 -51 -52 -53 -54 -55 -56 -57 -58 -59 -60 -61 -62 -63 -64\nleaf_value=0.022193873023561309 -0.0033631921021932566 -0.016672113941275692 0.12010871063056007 0.077704595345494468 0.14247539467086717 0.017415750612040932 -0.053836276784227269 0.19642302085456928 0.053382275947518279 0.021560385929285671 -0.063246086764964862 -0.035913488042556473 0.0065196091939426241 -0.068423003927101447 -0.057263112280900599 0.017532740476786914 0.036490410205219391 -0.0030364296425317034 0.054058421625928749 0.0064409788555576733 0.044711423977411437 0.15442192652142808 -0.036377655914682117 0.076976728683812418 0.032694800947982369 -0.068171478315641229 -0.053408863731421022 0.037083669227139765 -0.055008701297256171 0.0033366427482384945 0.0065325068231689223 0.0038799488585019408 0.13264944990275443 0.020859432582233883 -0.13592885585094058 -0.053052133156784156 -0.0085066035856952941 -0.086273871587600415 -0.016316987891924671 -0.017280272980824782 0.020387244035437235 0.10779466513816963 0.095196850608022493 0.16711260049646393 0.032204532794585357 -0.0003360206877814978 0.00097951599914770579 0.0084531614174746805 0.048998313704364735 -0.0089516496823466001 -0.071719041201499661 -0.020001733972561102 -0.033205537526731915 0.019764431233270437 -0.011219160105704678 0.041367857578498604 0.08608496960790181 0.065681092746173897 -0.019527653933509859 0.13267626599313109 -0.0015124739884987744 0.034274652317768592 0.058173144979383765\nleaf_weight=16391 230197 39453 10546 882484 7955 679418 158858 14766 43392 695250 34274 489289 14143 71985 1086579 85691 2962191 674249 848918 343034 899955 21848 433096 666694 30000 85876 148956 16839 75590 407748 389693 349141 9594 1784308 55246 46404 9000 308233 785949 3751364 4168 268366 515852 3138 1165879 348763 1381481 343282 368414 2428926 60000 127812 48000 896134 76001 62367 86224 633369 472003 167643 60133 423930 528518\nleaf_count=16391 230197 39453 10546 882484 7955 679418 158858 14766 43392 695250 34274 489289 14143 71985 1086579 85691 2962191 674249 848918 343034 899955 21848 433096 666694 30000 85876 148956 16839 75590 407748 389693 349141 9594 1784308 55246 46404 9000 308233 785949 3751364 4168 268366 515852 3138 1165879 348763 1381481 343282 368414 2428926 60000 127812 48000 896134 76001 62367 86224 633369 472003 167643 60133 423930 528518\ninternal_value=0.0129212 0.0446531 -0.0141298 0.0704534 -0.00584876 0.0293291 -0.0437333 0.0170206 -0.0393622 0.00209997 -0.0475823 -0.0301002 0.0906973 -0.0152595 -0.0565619 0.0161402 0.0359525 -0.000289606 0.0404037 -0.0170896 0.0582477 0.0650551 -0.0186794 0.0667121 -0.0526566 -0.0257122 -0.0721826 -0.0558233 -0.0147857 0.0086065 0.00952516 0.0187726 0.0230725 0.0207651 -0.108101 -0.00447151 0.101502 -0.0755662 -0.0223128 -0.017964 0.157672 0.102443 0.0928305 -0.00313131 0.0267595 -0.015839 -0.00392982 0.0114886 0.065605 -0.00535106 -0.0360443 -0.0387511 -0.00785925 0.0146272 -0.0330546 0.0739306 0.112198 0.0595459 -0.0275905 0.117362 -0.0321484 0.0234348 0.0496921\ninternal_weight=3.0135e+07 1.38677e+07 1.62673e+07 5.16747e+06 1.27115e+07 8.7002e+06 3.55583e+06 3.04379e+06 3.08225e+06 6.89102e+06 1.92375e+06 652814 1.94371e+06 5.82048e+06 1.27094e+06 3.02486e+06 5.65641e+06 6.18618e+06 3.81111e+06 5.42024e+06 3.22376e+06 1.79528e+06 5.07721e+06 1.75269e+06 1.18142e+06 1.1585e+06 473580 1.10342e+06 237282 1.97813e+06 400239 2.78758e+06 704844 2.55738e+06 89520 4.20805e+06 1.06123e+06 457189 1.07262e+06 5.00523e+06 18934 1.05223e+06 529995 42591 1.8453e+06 4.10013e+06 4.16164e+06 351237 1.73084e+06 3.81041e+06 609422 286670 78000 1.30388e+06 151591 729061 522233 1.00178e+06 905099 436009 549422 2.20824e+06 1.42847e+06\ninternal_count=30135000 13867666 16267334 5167468 12711507 8700198 3555827 3043792 3082247 6891023 1923752 652814 1943712 5820484 1270938 3024858 5656406 6186179 3811109 5420245 3223756 1795283 5077211 1752692 1181418 1158495 473580 1103418 237282 1978131 400239 2787576 704844 2557379 89520 4208048 1061228 457189 1072619 5005226 18934 1052228 529995 42591 1845297 4100127 4161644 351237 1730844 3810407 609422 286670 78000 1303882 151591 729061 522233 1001783 905099 436009 549422 2208238 1428473\nis_linear=0\nshrinkage=1\n\n\nTree=1\nnum_leaves=64\nnum_cat=0\nsplit_feature=5 3 4 0 4 3 6 34 39 1 26 2 37 34 1 7 37 32 0 37 4 39 7 34 33 38 34 19 38 38 37 39 37 3 19 34 38 37 27 38 4 6 37 38 37 26 39 28 37 19 22 29 33 6 6 7 39 22 38 7 6 6 38\nsplit_gain=9.3381e+06 1.97928e+06 1.43964e+06 469933 343261 256048 159631 134762 124849 124670 117917 99357.9 95676.4 93960.6 83707.1 83081.4 83044.2 103230 80046 74609.7 73542.9 70829.3 64575.6 60363.4 55783.9 54593.1 52236.9 69894.9 50057.4 49751.7 46001 44384.4 43425 41616.9 41474.5 40095 39257.6 39157.6 37731 35963 35305.1 34030.1 33355.8 50414.1 33320.9 32844.1 32352.7 29471.8 28875.8 28713.8 28599.1 28546.5 26215.9 35377.6 24430.4 32687 24360 24247.1 22168.1 22123.2 21874.7 21567 33923.9\nthreshold=14416946.736946179 20161130.627111416 9056328.644662844 29112122.230410449 11616213.317655139 14958999.809582122 7111440.8723937143 1.5979526577557539 0.30278504926614203 18195779.816106699 0.73259469188591897 36741331.18986883 4.5000000000000009 1.2979714412389571 15043296.962258082 14485972.534425847 3.5000000000000004 0.56621708230833234 20033454.84961148 56.500000000000007 19087489.874531139 0.93279414789000026 7803394.1269464865 1.1113785898379127 1.1754824317682946 0.93894197835419635 1.6751872954107829 0.41621599585953301 -0.16289508573225173 -0.96759678964602525 57.500000000000007 -0.97185599510546894 22.500000000000004 11665058.256763408 0.37177473135388911 1.333428943771364 -0.33996843066449761 16.500000000000004 0.63373506378408362 -0.53913703985740902 30566715.910917524 16571598.244283671 5.5000000000000009 -0.8819191655321561 44.500000000000007 0.77667571027873106 -0.61393937768005358 0.57325368230781815 20.500000000000004 0.85030670123886143 1.0455299329645895 0.48046710204423754 0.83367618160033308 13667540.195714748 13667540.195714748 12263250.820349583 0.68359067519442895 0.46473501518604693 0.33586178861854904 42591841.319631867 11411213.239607284 11499176.580465056 -0.97081889804462873\ndecision_type=2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2\nleft_child=2 5 6 18 12 7 25 13 23 15 21 -5 29 31 41 35 17 -12 26 22 -16 -10 -14 36 -15 -1 27 -3 -17 -4 32 -2 -18 -33 -28 42 61 -27 51 -29 -20 57 43 -6 -9 -36 -44 -32 -40 -30 60 -24 -31 -54 -11 -56 -35 -7 -41 -47 -38 -8 -63\nright_child=1 3 4 11 9 14 8 44 10 54 16 -13 19 24 20 28 30 -19 40 -21 -22 -23 38 -25 -26 37 34 39 49 52 47 33 -34 56 45 -37 50 -39 48 58 -42 -43 46 -45 -46 59 -48 -49 -50 -51 -52 -53 53 -55 55 -57 -58 -59 -60 -61 -62 62 -64\nleaf_value=0.0088090505225463002 -0.015470160256362747 -0.026875398596082258 0.10182814737176071 0.067068017721330087 0.12307649438670419 -0.074426608536777072 -0.051292177183946845 0.051587267151490847 -0.055514379343908939 0.0031458154982149859 0.038990973366163473 0.093051201241920026 -0.077276981245355231 -0.0063255628457869169 0.022449645334100168 -0.015159736117407566 -0.047340582687084617 -0.047627340042113275 0.049190537413896375 -0.0061561982570827109 0.039245309854550874 -0.15273003473332336 -0.12252390791797436 -0.077038031447233035 -0.055624290475551508 -0.063013548458198593 0.13161360008356351 0.044771272538056843 -0.006084891890902739 -0.035012665552573458 0.01878493298595936 -0.0085891763173518917 -0.065268971257373354 0.012893464151149826 0.13574522957100391 -0.073826564809972836 -0.021961140082439407 -0.094235306713931849 -0.022062356470297612 0.01923475652062959 0.06754734413342349 0.018391279684685648 -0.011344588216127644 -0.0042446248844037063 0.17809724124972848 0.023710245444791913 -0.020916805989957529 -0.046083531281498516 -0.031226731362154245 0.008765448637675196 -0.038583053411802876 -0.044428994737214803 -0.0081499526448121761 0.0389104222421729 0.11390222420558133 0.019087113678090441 0.00049609926468687578 0.0055728492491861096 0.03605217462601145 0.14124533883780713 0.010484362556331991 0.057754093578110503 -0.034924733584585581\nleaf_weight=16391 230197 43460 10546 858146 7955 9605 330551 8627 29740 473918 50136 644059 71985 134249 2928803 674249 481771 109574 1532629 343034 838310 50638 18231 85876 100219 148956 24297 830290 627322 75439 30000 349141 1129837 1690707 9898 30306 310305 308233 1115065 300618 315920 1197496 1381481 343282 13121 40905 2445024 42056 3750967 676560 242755 32673 357588 44956 9479 221447 517531 682192 562808 4438 62394 10794 115820\nleaf_count=16391 230197 43460 10546 858146 7955 9605 330551 8627 29740 473918 50136 644059 71985 134249 2928803 674249 481771 109574 1532629 343034 838310 50638 18231 85876 100219 148956 24297 830290 627322 75439 30000 349141 1129837 1690707 9898 30306 310305 308233 1115065 300618 315920 1197496 1381481 343282 13121 40905 2445024 42056 3750967 676560 242755 32673 357588 44956 9479 221447 517531 682192 562808 4438 62394 10794 115820\ninternal_value=9.75005e-12 0.0301453 -0.0256985 0.0546556 -0.0178315 0.0155875 -0.0538218 0.00389443 -0.0496692 -0.0102802 -0.0574783 0.0782081 -0.0267716 0.00300194 0.0218797 -0.0125503 -0.0548934 -0.0204362 0.0450026 -0.028712 0.0261872 -0.11676 -0.030263 -0.0367017 -0.0273974 -0.0808486 0.0375491 0.035735 -0.00409896 -0.00559334 -0.0581619 0.00555888 -0.0599095 0.00745176 0.0771724 -0.0165231 -0.0334723 -0.084063 -0.0295747 0.0373415 0.0523277 0.0132909 -0.0161074 -0.00136099 0.127913 0.0532271 -0.017461 -0.019076 -0.0291267 0.00162067 -0.0252281 -0.0723983 -0.00796344 -0.00289426 0.00964373 0.0229791 0.00998797 0.00446213 0.0301969 0.0352141 -0.0165294 -0.0445709 -0.0270237\ninternal_weight=3.0135e+07 1.38677e+07 1.62673e+07 5.16747e+06 1.27115e+07 8.7002e+06 3.55583e+06 3.04379e+06 3.08225e+06 6.89102e+06 1.92375e+06 1.5022e+06 5.82048e+06 3.02204e+06 5.65641e+06 6.18618e+06 1.84337e+06 159710 3.66526e+06 5.33196e+06 3.76711e+06 80378 4.98892e+06 1.1585e+06 234468 473580 1.81671e+06 1.73718e+06 1.97813e+06 488529 1.68366e+06 2.78758e+06 1.61161e+06 2.55738e+06 79538 4.20805e+06 1.07262e+06 457189 4.91694e+06 1.69372e+06 1.84855e+06 1.88929e+06 4.17774e+06 351237 21748 55241 3.8265e+06 72056 4.86603e+06 1.30388e+06 615454 50904 477983 402544 704844 230926 2.20824e+06 691797 863426 45343 372699 457165 126614\ninternal_count=30135000 13867666 16267334 5167468 12711507 8700198 3555827 3043792 3082247 6891023 1923752 1502205 5820484 3022044 5656406 6186179 1843374 159710 3665263 5331955 3767113 80378 4988921 1158495 234468 473580 1816714 1737176 1978131 488529 1683664 2787576 1611608 2557379 79538 4208048 1072619 457189 4916936 1693716 1848549 1889293 4177742 351237 21748 55241 3826505 72056 4866032 1303882 615454 50904 477983 402544 704844 230926 2208238 691797 863426 45343 372699 457165 126614\nis_linear=0\nshrinkage=0.05\n\n\nTree=2\nnum_leaves=64\nnum_cat=0\nsplit_feature=5 3 3 1 3 3 39 6 34 6 27 3 1 34 37 1 37 35 5 39 34 1 6 5 5 39 37 39 9 35 37 37 37 1 35 39 39 3 37 5 6 37 31 34 31 34 26 35 35 27 5 24 39 24 37 5 22 6 39 39 5 39 27\nsplit_gain=8.4277e+06 1.80332e+06 1.25641e+06 423455 236220 211743 197236 156549 124211 117405 102786 91583.5 87521.1 86868.8 85183.2 79009.6 74174.9 72272.7 61302.6 60240.6 57883.4 72198.1 54642.6 49043.1 49033.6 46348.1 52362.5 45667.8 42182.8 41998.9 41825.6 44503.4 41775 41468.7 40274.8 39589.9 38054 37831.3 34361.8 34191.3 33885.2 32208.5 29616 29316.7 29209.1 28758.3 29542.8 28969.1 28379.1 28229.4 27444.5 26016.9 23832.1 23790.3 23132 22978.6 21612.3 21582 21358.5 21245 21181.6 20536.2 20396.3\nthreshold=14336201.528303774 20161130.627111416 9250534.10419981 27339675.977263708 14832286.669400102 12574469.691562243 -0.33586178861854904 7111440.8723937143 1.5979526577557539 13599685.284667684 0.47996931568723478 35116259.166666858 18303954.205510996 1.2979714412389571 17.500000000000004 14976308.95729433 56.500000000000007 1.13531340328763 18133876.575773533 0.96304284483113523 1.7437128063291494 11348614.082808359 7932322.4432381913 13052674.773380799 11167145.749977002 0.30278504926614203 3.5000000000000004 0.6035545055974717 0.58699672937251612 1.1408296858543132 6.5000000000000009 49.500000000000007 5.5000000000000009 21367844.180752996 1.2166131206393145 -0.20364175114017743 -0.97185599510546894 11707898.529924927 16.500000000000004 9236670.2993365433 16571598.244283671 4.5000000000000009 0.6339036363063203 1.6451868642645495 1.3777198692592083 0.91713332681025139 1.0479666575990525 1.2278614130076118 0.76967643494868809 1.1776968571928754 10837011.813865224 1.0267936769828581 -0.98285265264473198 1.4481755746637972 2.5000000000000004 18780903.275874794 0.46473501518604693 15819544.119628603 -0.17149884075797744 0.17149884075797728 57571290.240378231 -0.87567323142345155 1.1586399267266041\ndecision_type=2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2\nleft_child=2 4 6 20 8 9 22 38 13 14 19 55 32 36 29 40 39 25 -17 -9 21 -3 49 42 48 58 -27 59 30 50 -13 60 -7 -23 -14 -34 -2 61 -8 51 56 -26 -19 -30 -10 46 -37 -47 -11 -1 53 -16 -20 -4 -39 -5 -6 -54 -12 -15 -32 -38 -22\nright_child=1 3 5 11 15 12 7 10 44 24 17 28 34 27 16 18 -18 23 52 -21 62 33 -24 -25 41 26 -28 -29 43 -31 31 -33 35 -35 -36 45 37 54 -40 -41 -42 -43 -44 -45 -46 47 -48 -49 -50 -51 -52 -53 57 -55 -56 -57 -58 -59 -60 -61 -62 -63 -64\nleaf_value=-0.06488440836992003 -0.014653177060941717 -0.015213182080520353 -0.022313698183055973 0.041390900976869364 -0.070703984325206096 0.0056120664557161443 -0.060631708466639525 -0.11176167887407083 0.15204010260413464 -0.10235326262349942 -0.057288907062425447 0.11766199255653792 0.0075137863655417806 -0.015593809148975003 -0.070426516134902445 0.01952660153027334 -0.0025667055539043051 0.04572620438231989 0.12498487336748398 0.002460471773224511 0.14028203566658257 0.035231508635152078 -0.023798372871768388 -0.10812508943384871 0.026608542490695875 -0.024030952139207244 -0.054553938381746631 -0.052311428130410759 0.082330678575410932 -0.067001215196877489 0.038472084842224398 0.10462755792236354 -0.0065684832766610126 0.04673488048306184 0.10827736733271243 0.0016998958860121136 0.021812960162555892 0.029841190555136905 -0.089871697198838696 -0.028404677708564165 0.017412195642886583 -0.0061976555215478586 -0.014188230692524015 0.10816104415213242 0.0045133896400191926 -0.022976985062782503 -0.018606493636791795 0.12466144879730551 -0.028027352385248457 0.0080911757882554877 -0.0073235724385487134 -0.036054215206565668 -0.025597911941538584 0.023151098724039962 0.0078746939521672759 0.063788964058796582 0.0047692957903707868 0.032537245651497779 -0.032712995730609887 0.042998387910341676 -0.027817429234027566 -0.012704292900321327 0.065531955682766749\nleaf_weight=126349 229868 58068 700927 128919 9611 366572 149362 91825 17205 14461 106362 17500 672951 113243 82946 2361456 271270 27087 6911 13203 18469 1547996 911238 11530 80767 151520 1933661 101067 575228 37246 25242 15321 1656354 15