In [1]:
import pandas as pd

df = pd.read_parquet("/data/sigma/zzy/janus/results/vol_pred_prod/features/XRPUSDT_2026-01-01_features.parquet")
df

,ts,vol_1m,vol_3m,vol_5m,vol_10m,vol_15m,vol_30m,vol_60m,vol_120m,vol_ratio_5_30,vol_ratio_30_120,hour,minute,tod_sin,tod_cos,y_vol_5m
0,1767225600000000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.000000,1.00000,0.0
1,1767225600020000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.000000,1.00000,0.0
2,1767225600040000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.000000,1.00000,0.0
3,1767225600060000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.000000,1.00000,0.0
4,1767225600080000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.000000,1.00000,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4319995,1767311999900000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,23.0,59.0,-0.004363,0.99999,NaN
4319996,1767311999920000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,23.0,59.0,-0.004363,0.99999,NaN
4319997,1767311999940000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,23.0,59.0,-0.004363,0.99999,NaN
4319998,1767311999960000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,23.0,59.0,-0.004363,0.99999,NaN
4319999,1767311999980000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,23.0,59.0,-0.004363,0.99999,NaN

In [5]:
df.describe()

,ts,vol_1m,vol_3m,vol_5m,vol_10m,vol_15m,vol_30m,vol_60m,vol_120m,vol_ratio_5_30,vol_ratio_30_120,hour,minute,tod_sin,tod_cos,y_vol_5m
count,4.320000e+06,4317000.0,4311000.0,4305000.0,4290000.0,4275000.0,4230000.0,4140000.0,3960000.0,0.0,0.0,4.320000e+06,4.320000e+06,4.320000e+06,4.320000e+06,4305000.0
mean,1.767269e+18,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,1.150000e+01,2.950000e+01,9.689574e-17,-2.757958e-17,0.0
std,2.494153e+13,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,6.922187e+00,1.731810e+01,7.071069e-01,7.071069e-01,0.0
min,1.767226e+18,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,0.000000e+00,0.000000e+00,-1.000000e+00,-1.000000e+00,0.0
25%,1.767247e+18,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,5.750000e+00,1.475000e+01,-7.071068e-01,-7.071068e-01,0.0
50%,1.767269e+18,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,1.150000e+01,2.950000e+01,6.123234e-17,-6.123234e-17,0.0
75%,1.767290e+18,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,1.725000e+01,4.425000e+01,7.071068e-01,7.071068e-01,0.0
max,1.767312e+18,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,2.300000e+01,5.900000e+01,1.000000e+00,1.000000e+00,0.0